version: "3.8"
services:
  db:
    image: "mysql:latest"
    container_name: lolmood_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./src/database/database.sql:/docker-entrypoint-initdb.d/database.sql
  api:
    build: .
    container_name: lolmood_api
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
      API_KEY: ${API_KEY}
    ports:
      - "3000:3000"