export * from "./getUpdatedAccount";
export * from "./getUpdatedRank";
export * from "./returnStoredAccount";
export * from "./returnMatches";
export * from "./convertRegion";
export * from "./getStoredAccount";
export * from "./verifParams";
export * from "./updateAccountInDB";
export * from "./updateGameInDB";